// 截图收录日期与评价日期分别保存；未知分店名、地址和距离不编造。
window.RESTAURANTS = [
  {
    "id": "a3427c4fed436083e011037f",
    "name": "柳州老牌螺蛳粉(信息学院店)",
    "address": "湖南省长沙市望城区电子街78号",
    "category": "螺蛳粉",
    "distanceM": 71,
    "checkedAt": "2026-10-03",
    "reviewDate": "2026-09-17",
    "status": "有今年评价",
    "url": "https://map.baidu.com/poi/%E6%9F%B3%E5%B7%9E%E8%80%81%E7%89%8C%E8%9E%BA%E8%9B%B3%E7%B2%89(%E4%BF%A1%E6%81%AF%E5%AD%A6%E9%99%A2%E5%BA%97)/@12559774.96,3272252.94,13z?uid=a3427c4fed436083e011037f&ugc_type=3&ugc_ver=1&device_ratio=2&compat=1&en_uid=a3427c4fed436083e011037f&pcevaname=pc4.1&querytype=detailConInfo&da_src=shareurl",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址"
  },
  {
    "id": "xiaojiaoqing",
    "name": "小椒情时尚简餐",
    "address": "湖南省长沙市望城区乌山街道电子街76号",
    "category": "中餐馆",
    "distanceM": 71,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址"
  },
  {
    "id": "screenshot-20261004-01",
    "name": "辰之美早餐店",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "早餐",
    "distanceM": 100,
    "distanceQualifier": "lt",
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 1,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "shandangjia",
    "name": "膳当家黄焖鸡米饭(湖南信息职院店)",
    "address": "乌山街道聚缘路26号（近职业技术学校南院）",
    "category": "黄焖鸡",
    "distanceM": 102,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址",
    "screenshotIndex": 69,
    "screenshotDistanceM": 255,
    "screenshotAddedAt": "2026-10-04"
  },
  {
    "id": "screenshot-20261004-65",
    "name": "我家味道",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "中餐",
    "distanceM": 110,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 65,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-53",
    "name": "常来往(喻家坡小区店)",
    "address": "长沙市望城区喻家坡小区（具体门牌待核对）",
    "category": "快餐",
    "distanceM": 173,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 53,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "chenshi",
    "name": "陈氏酱板鸭",
    "address": "长沙市望城区郭亮南路23号",
    "category": "卤味",
    "distanceM": 205,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址",
    "screenshotIndex": 9,
    "screenshotDistanceM": 439,
    "screenshotAddedAt": "2026-10-04"
  },
  {
    "id": "screenshot-20261004-54",
    "name": "煲味煲仔饭(望城店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "煲仔饭",
    "distanceM": 216,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 54,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-10",
    "name": "临榆炸鸡腿(信息职院店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "炸鸡",
    "distanceM": 228,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 10,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-02",
    "name": "塔斯汀中国汉堡",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "汉堡",
    "distanceM": 232,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 2,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 232 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-63",
    "name": "祥哥家厨土菜馆",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "土菜",
    "distanceM": 239,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 63,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-73",
    "name": "火爆爆新疆炒米粉(望城店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "炒米粉",
    "distanceM": 243,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 73,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-47",
    "name": "懒人族猪脚烧腊饭(高塘览胜店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "猪脚饭",
    "distanceM": 245,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 47,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-21",
    "name": "百味粉店",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "米粉",
    "distanceM": 248,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 21,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-72",
    "name": "好享吃餐厅",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "中餐",
    "distanceM": 248,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 72,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "yanyangxuan",
    "name": "艳阳轩私房菜",
    "address": "湖南省长沙市望城区前进路21号",
    "category": "私房菜",
    "distanceM": 268,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址"
  },
  {
    "id": "screenshot-20261004-20",
    "name": "中国兰州拉面(高塘览胜店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "拉面",
    "distanceM": 269,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 20,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-27",
    "name": "沙县小吃",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "沙县小吃",
    "distanceM": 269,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 27,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-41",
    "name": "隆江猪脚饭郴州杀猪粉",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "猪脚饭",
    "distanceM": 278,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 41,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 278 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-67",
    "name": "隆江猪脚饭(高塘览胜店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "猪脚饭",
    "distanceM": 300,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 67,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-50",
    "name": "黄蜀郎鸡公煲",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "鸡公煲",
    "distanceM": 307,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 50,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-17",
    "name": "沙县小吃(安子坡小区店)",
    "address": "长沙市望城区安子坡小区（具体门牌待核对）",
    "category": "沙县小吃",
    "distanceM": 322,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 17,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-68",
    "name": "米汤饭",
    "address": "湖南省长沙市望城区郭亮南路55号附近（历史地址，待核对）",
    "category": "快餐",
    "distanceM": 349,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 68,
    "nameStatus": "截图完整店名",
    "addressStatus": "历史地图地址，待核对",
    "branchNote": null,
    "url": "https://changsha.city8.com/cater/84hn2u767c3ybad9f4",
    "addressSourceDate": "2022-07-13"
  },
  {
    "id": "screenshot-20261004-16",
    "name": "绝味鸭脖(才子城店)",
    "address": "长沙市望城区才子城（具体门牌待核对）",
    "category": "卤味",
    "distanceM": 371,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 16,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-59",
    "name": "新疆丝带路壹羊羊羊肉",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "羊肉烧烤",
    "distanceM": 385,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 59,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 385 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-44",
    "name": "林木木自助快餐",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "快餐",
    "distanceM": 397,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 44,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-42",
    "name": "杭州小笼包(才子府店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "小笼包",
    "distanceM": 415,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 42,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-49",
    "name": "遵义·老牌牛羊肉粉馆(才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "牛羊肉粉",
    "distanceM": 422,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 49,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-03",
    "name": "功夫煲仔饭(聚缘路店)",
    "address": "长沙市望城区聚缘路（具体门牌待核对）",
    "category": "煲仔饭",
    "distanceM": 423,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 3,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-22",
    "name": "宁乡宁手工鸡蛋面(才子府店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "面食",
    "distanceM": 425,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 22,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-08",
    "name": "薛笑笑螺蛳粉(才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "螺蛳粉",
    "distanceM": 433,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 8,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-40",
    "name": "等笼灯·益阳麻辣烫",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "麻辣烫",
    "distanceM": 443,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 40,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 443 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-29",
    "name": "张十三益阳麻辣烫",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "麻辣烫",
    "distanceM": 444,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 29,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 444 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-43",
    "name": "喜淘好饭",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "快餐",
    "distanceM": 450,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 43,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-35",
    "name": "兰州拉面",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "拉面",
    "distanceM": 456,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 35,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-45",
    "name": "鲜记开心湘乡银丝粉",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "米粉",
    "distanceM": 488,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 45,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 488 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-13",
    "name": "菌山集·云南野生菌火锅(才子汇店)",
    "address": "长沙市望城区才子汇购物中心（具体铺位待核对）",
    "category": "火锅",
    "distanceM": 489,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 13,
    "nameStatus": "已查到完整店名",
    "addressStatus": "已识别商场，铺位待核对",
    "branchNote": null,
    "url": "https://www.douyin.com/video/7682342753921501126"
  },
  {
    "id": "screenshot-20261004-07",
    "name": "S-pizza披萨速递(望城店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "披萨",
    "distanceM": 510,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 7,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-51",
    "name": "焦本味·铁板焦饭·意面",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "铁板饭",
    "distanceM": 516,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 51,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 516 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-58",
    "name": "摸鱼脆皮烤鱼",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "烤鱼",
    "distanceM": 517,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 58,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-48",
    "name": "衡湘君高压锅盖码饭(才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "盖码饭",
    "distanceM": 520,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 48,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-61",
    "name": "田园特色粉面馆",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "粉面",
    "distanceM": 525,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 61,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-64",
    "name": "搭饭(长沙望城才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "湘菜",
    "distanceM": 529,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 64,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-66",
    "name": "东北饺子馆(信息店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "饺子",
    "distanceM": 529,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 66,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "dawan",
    "name": "大碗先生(才子汇店)",
    "address": "乌山街道高塘岭大道才子府23栋3层3027号商铺",
    "category": "湘菜",
    "distanceM": 538,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址",
    "screenshotIndex": 24,
    "screenshotDistanceM": 571,
    "screenshotAddedAt": "2026-10-04"
  },
  {
    "id": "screenshot-20261004-25",
    "name": "唐记同福·金汤酸菜鱼",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "酸菜鱼",
    "distanceM": 543,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 25,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 543 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "jianggu",
    "name": "江古六·老北京涮牛羊肉(才子汇店)",
    "address": "长沙市望城区才子汇3楼",
    "category": "火锅",
    "distanceM": 561,
    "checkedAt": "2026-10-03",
    "reviewDate": null,
    "status": "用户指定加入",
    "url": "https://j.map.baidu.com/t/M1Ffrv",
    "distanceSource": "百度地图周边查询",
    "nameStatus": "完整店名",
    "addressStatus": "原名单地图地址"
  },
  {
    "id": "screenshot-20261004-05",
    "name": "彭耕记猪油炒小菜(才子汇店)",
    "address": "长沙市望城区乌山街道高塘岭大道与喻家坡交叉东北角才子府23号栋3层3024号",
    "category": "湘菜",
    "distanceM": 562,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 5,
    "nameStatus": "已查到完整店名",
    "addressStatus": "已查到地图地址",
    "branchNote": null,
    "url": "https://www.amap.com/place/B0KAYU0M1P"
  },
  {
    "id": "screenshot-20261004-18",
    "name": "笨小钵·酱板鸭炖牛蛙",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "湘菜",
    "distanceM": 566,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 18,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 566 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-32",
    "name": "鲜目录·中国寿司",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "寿司",
    "distanceM": 569,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 32,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 569 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-04",
    "name": "市井边边旋转小火锅",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "小火锅",
    "distanceM": 570,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 4,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 570 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-46",
    "name": "富得牛牛自助烤肉",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "烤肉",
    "distanceM": 575,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 46,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 575 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-06",
    "name": "霸碗盖码饭",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "盖码饭",
    "distanceM": 580,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 6,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 580 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-14",
    "name": "喜皇",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "汉堡",
    "distanceM": 580,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 14,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-37",
    "name": "正新鸡排(才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "炸鸡",
    "distanceM": 587,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 37,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-26",
    "name": "许府牛火锅",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "牛肉火锅",
    "distanceM": 607,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 26,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 607 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-34",
    "name": "大米先生(才子汇店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "快餐",
    "distanceM": 617,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 34,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-15",
    "name": "肯德基(长沙才子府店)",
    "address": "长沙市望城区才子府 / 才子汇（具体铺位待核对）",
    "category": "快餐",
    "distanceM": 622,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 15,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-19",
    "name": "尊宝比萨(才子城店)",
    "address": "长沙市望城区才子城（具体门牌待核对）",
    "category": "披萨",
    "distanceM": 643,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 19,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-33",
    "name": "嗨才夜生活市集",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "美食市集",
    "distanceM": 658,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 33,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-39",
    "name": "水城羊肉粉才子城店",
    "address": "长沙市望城区才子城（具体门牌待核对）",
    "category": "羊肉粉",
    "distanceM": 668,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 39,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-23",
    "name": "绿草地·湘菜",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "湘菜",
    "distanceM": 671,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 23,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 671 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-62",
    "name": "飞扬锅锅",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "干锅",
    "distanceM": 679,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 62,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-36",
    "name": "北京烤鸭",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "烤鸭",
    "distanceM": 748,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 36,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-52",
    "name": "小串炭火烧烤",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "烧烤",
    "distanceM": 752,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 52,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-71",
    "name": "华莱士·全鸡汉堡",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "汉堡",
    "distanceM": 755,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 71,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 755 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-28",
    "name": "新疆味道羊肉烧烤店",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "烧烤",
    "distanceM": 758,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 28,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-70",
    "name": "刘聋子粉店",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "米粉",
    "distanceM": 822,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 70,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-60",
    "name": "东北铁锅炖饺子馆",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "东北菜",
    "distanceM": 884,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 60,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 884 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-55",
    "name": "徐大川剁椒猪脚饭",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "猪脚饭",
    "distanceM": 903,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 55,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 903 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-31",
    "name": "何记夜宵(总店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "夜宵",
    "distanceM": 911,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 31,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-56",
    "name": "罗记常德牛肉粉面(景城苑店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "牛肉粉面",
    "distanceM": 924,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 56,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-12",
    "name": "油麻港辣子鸡手擀面",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "面食",
    "distanceM": 947,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 12,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 947 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-57",
    "name": "柯柯快餐",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "快餐",
    "distanceM": 953,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 57,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-11",
    "name": "塔斯汀中国汉堡",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "汉堡",
    "distanceM": 960,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 11,
    "nameStatus": "分店全名待核对",
    "addressStatus": "具体地址待核对",
    "branchNote": "截图中约 960 米的门店，分店全名待核对",
    "url": null
  },
  {
    "id": "screenshot-20261004-38",
    "name": "沙县小吃(职忠路店)",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "沙县小吃",
    "distanceM": 970,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 38,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-30",
    "name": "刘文祥大碗麻辣烫",
    "address": "长沙市望城区（具体地址待核对）",
    "category": "麻辣烫",
    "distanceM": 976,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 30,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  },
  {
    "id": "screenshot-20261004-74",
    "name": "三津汤包(才子城店)",
    "address": "长沙市望城区才子城（具体门牌待核对）",
    "category": "汤包",
    "distanceM": null,
    "distanceQualifier": null,
    "distanceSource": "用户截图中的地图搜索距离",
    "checkedAt": "2026-10-04",
    "reviewDate": null,
    "status": "用户截图收录",
    "sourceKind": "screenshot",
    "sourceNote": "2026-10-04 用户提供的地图截图",
    "screenshotIndex": 74,
    "nameStatus": "截图完整店名",
    "addressStatus": "具体地址待核对",
    "branchNote": null,
    "url": null
  }
];
